### ISSUE TITLE
Startup script for Github Runner?

### ISSUE THREAD

**Issue by jwcmd** [terraform-google-modules/terraform-google-github-actions-runners#12]
It looks like this sets up a MIG, an autoscaler, an instance template, and even a secret in GCP SM but... it doesn't seem to do anything with the secret?

The startup script variable defaults to blank, I was thinking the module would include a startup script that would download the values from the secret, and install+configure a github actions runner.

Apologies if I've missed the section that does this, I *have* gone looking but I can't find it.

**Comment by bharathkkb** [comment]
Hi @jwcmd 
The startup script is passed in by the user and we have an example showcased here with both startup and shutdown scripts. I do think it makes sense to provide a default script out of the box with the module, as this would be the expectation of the end user.
 
https://github.com/terraform-google-modules/terraform-google-github-actions-runners/blob/master/examples/gh-runner-mig-native-simple
