### ISSUE TITLE
Github Organization level runner support

### ISSUE THREAD

**Issue by kopachevsky** [terraform-google-modules/terraform-google-github-actions-runners#25]
Hi, I need to setup runner to be shared accross multiple repos in organizaton, is current module support this?

**Comment by bharathkkb** [comment]
Hi @kopachevsky 
Yes it can support it, but you will need to modify the startup script (if using VM runners) via `var.startup_script`.
You will need to modify https://github.com/terraform-google-modules/terraform-google-github-actions-runners/blob/3b391618839d59ff6925305577a04c28011ed084/modules/gh-runner-mig-vm/scripts/startup.sh#L46 to remove the `${REPO_NAME}` to conform to https://docs.github.com/en/rest/reference/actions#create-a-registration-token-for-an-organization--code-samples

Also happy to accept a PR that can add some of the logic into the script like if `REPO_NAME` is empty, get org runner registration token.

**Comment by bharathkkb** [comment]
Deduping to https://github.com/terraform-google-modules/terraform-google-github-actions-runners/issues/3
