### ISSUE TITLE
Authoritative IAM binding prevents use with shared role

### ISSUE THREAD

**Issue by tyler-jachetta** [terraform-google-modules/terraform-google-github-actions-runners#26]
https://github.com/terraform-google-modules/terraform-google-github-actions-runners/blob/3513d0269ddb32c8e8b0d9d01f265bbda286d18d/modules/gh-runner-gke/main.tf#L83

The use of `google_project_iam_binding` here ensures that in the given project, no other role/user can be in the role "roles/storage.objectViewer". This is undesirable in my case and seems like a not ideal thing to do as it seems likely to conflict with other terraform used to manage roles.
Proposed fix incoming

**Comment by bharathkkb** [comment]
fixed by https://github.com/terraform-google-modules/terraform-google-github-actions-runners/pull/27
