### ISSUE TITLE
Include example for Github Org

### ISSUE THREAD

**Issue by jwcmd** [terraform-google-modules/terraform-google-github-actions-runners#3]
There's a ton of examples already documented and I can't tell you how much I appreciate what's already there, thank you! 

That said, I'm looking to connect a self-hosted runner to an entire Github Org, it would be cool if we could use this against an Org.

If I'm able to find an incantation that works I'll gladly submit a PR :D

**Comment by bharathkkb** [comment]
Hi @jwcmd 
Looks like we need a small modification to support this. 
Currently we get the registration token here
https://github.com/terraform-google-modules/terraform-google-github-actions-runners/blob/efc45d31e6a33b406a6d5d4beff10d4b838d2736/modules/gh-runner-mig-vm/scripts/startup.sh#L46
This should be switched based on if org or repo, org endpoint is documented [here](https://developer.github.com/v3/actions/self-hosted-runners/#create-a-registration-token-for-an-organization). Within the TF code we can store the type of runner (org/repo) in the metadata and access that during runtime.

**Comment by rajcheval** [comment]
helpful module. I also need to add github runner to an org. I think adding to org is by far the most common use case for github runner so updating modules to support org along with adding an example will be great.

**Comment by jacek-jablonski** [comment]
+1, I would also like to use this module for org runners.

**Comment by bharathkkb** [comment]
Org runners (https://github.com/terraform-google-modules/terraform-google-github-actions-runners/pull/34) and examples (https://github.com/terraform-google-modules/terraform-google-github-actions-runners/pull/37) have been added.
