### ISSUE TITLE
Support multiple github action runners per compute instance

### ISSUE THREAD

**Issue by raj-saxena** [terraform-google-modules/terraform-google-github-actions-runners#38]
It might be useful in some cases to register multiple action runners on a large compute machine to parallelize jobs & utilise the remaining capacity of the instance while the instance-group is scaling up (which takes some time).

I have made & tested the changes in my fork (https://github.com/raj-saxena/terraform-google-github-actions-runners/pull/2/files). 
Example - 
```terraform
module "runner-mig" {
  source                     = "github.com/raj-saxena/terraform-google-github-actions-runners//modules/gh-runner-mig-vm?ref=1468894a76e090779f9a0a7a8d004722cf50a585"
  create_network             = true
  project_id                 = var.project_id
  repo_owner                 = var.repo_owner
  gh_token                   = var.gh_token
  gh_runner_instances_per_vm = 3
}
```

<img width="842" alt="Screenshot 2021-10-21 at 09 22 03" src="https://user-images.githubusercontent.com/6253803/138230698-15514a22-6398-44f8-89e6-dfd89f1f0c82.png">
<img width="1082" alt="Screenshot 2021-10-21 at 09 22 10" src="https://user-images.githubusercontent.com/6253803/138231206-d66af5ce-9266-4035-9abe-c85022a44c1f.png">

@bharathkkb Would this be something that you are interested in? If yes, I'll create a PR soon based on your reply.

**Comment by ustuehler-brands4friends** [comment]
I am not a maintainer of this project, but I would rather have multiple smaller instances on standby or use a different runtime (for example, GKE) to scale up runners quickly.

When multiple jobs are executing on the same machine, they might compete for resources and run unpredictably. Even worse, if the same runner VM accepts jobs from multiple repositories and/or workflows, secrets from one job could be leaked to another job that should not have access to them.

**Comment by raj-saxena** [comment]
Thanks for your feedback. 
Our main reason for avoiding GKE as the runtime is because some of our [jobs use container](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idcontainer) and run inside it. This creates the problem of running containers in action-runner-containers which has its own set of problems and [should be avoided](https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/).

While the concerns that you raise are true, we are comfortable accepting them as trade-offs in our organisation for now.

Assuming the same might be true for other users of the module, we wanted to have this flexibility into the module for users who understand the tradeoffs & are okay with it.
