### ISSUE TITLE
Name of GCP SM secret containing GH Token instead of GH Token

### ISSUE THREAD

**Issue by jwcmd** [terraform-google-modules/terraform-google-github-actions-runners#4]
Right now the module takes the Github Token as a direct parameter, and then deposits it into a GCP-SM Secret.

Putting the Github token in plaintext in our terraform repo is poor form, so I've put it into a GCP SM already outside of this module, I then use a data source to extract that secret and pass it into the module. It doesn't seem necessary for the module to then create a new GCP SM secret to put the key into.

Ideally, I could just pass in the name (and GCP Project) of the GCP SM secret containing the Github Token.

Again I just wanna say that I'm loving the module, I hope you don't mind my filing issues, I do intend to upstream my fixes if I patch anything myself. Cheers!

**Comment by bharathkkb** [comment]
Thank for all the feedback @jwcmd and feel free to upstream. I think this is a great idea, will try to get to it soon

**Comment by jwcmd** [comment]
I hadn't realized that it was more than just that token in the secret created by this module, now that I've tucked into the module a bit I can see that this not only isn't as trivial as I expected, it perhaps isn't worth the effort to make this change at all - where would the other secret values go, into their own secret? That seems wasteful in hindsight.

My apologies, closing this issue out, I should have dug into the code more before filing this issue.
